version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: ms-orders
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_VHOST=/

  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "orders"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/data/db